###

# curl -X POST -H "Content-Type: application/json" -d '{"message":"Funciona"}' http://localhost:8081/api/v1/messages
POST http://localhost:8081/api/v1/messages
Content-Type: application/json

{
  "message": "Funciona"
}

###

# curl -X POST -H "Content-Type: application/json" -d '{"message":"Funciona"}' http://localhost:8081/api/v1/messages
POST http://localhost:8082/api/v1/messages
Content-Type: application/json

{
  "message": "Funciona"
}

###

# curl -X POST -H "Content-Type: application/json" -d '{"message":"Funciona"}' http://localhost:8081/api/v1/messages
POST http://localhost:8083/api/v1/messages
Content-Type: application/json

{
  "message": "Funciona"
}

###

# curl -X POST -H "Content-Type: application/json" -d '{"message":"Funciona"}' http://localhost:8081/api/v1/messages
POST http://localhost:8084/api/v1/messages
Content-Type: application/json

{
  "message": "Funciona"
}

###




